name: 'Setup Environment'
description: 'Sets up Node.js, corepack, and installs dependencies based on the build variant'
inputs:
    variant:
        description: 'The build variant (default or foss)'
        required: true
        default: 'default'

runs:
    using: "composite"
    steps:
        - name: Enable Corepack
          run: corepack enable
          shell: bash

        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
              node-version: 24
              cache: 'yarn'

        - name: Install dependencies (Default Variant)
          if: inputs.variant == 'default'
          run: yarn install --immutable
          shell: bash

        - name: Prepare and Install Dependencies (FOSS Variant)
          if: inputs.variant == 'foss'
          run: |
              sudo apt-get install -y jq
              jq 'del(.dependencies["expo-location", "expo-notifications"])' package.json > temp.json && mv temp.json package.json
              yarn install --no-immutable
          shell: bash

        - name: Generate License Information Check
          run: yarn generate-licenses
          shell: bash
