name: PR Validation

on:
    pull_request:
        types: [opened, synchronize, reopened]
        branches:
            - 'main'

permissions:
    contents: read

jobs:
    validate:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                variant: [default, foss]

        steps:
            - name: Checkout code
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

            - name: Setup Environment and Install Dependencies
              uses: ./.github/actions/setup-environment
              with:
                  variant: ${{ matrix.variant }}

            - name: Typecheck
              if: matrix.variant == 'default'
              run: yarn typecheck

            - name: Lint
              if: matrix.variant == 'default'
              run: yarn lint

            - name: Prettier
              if: matrix.variant == 'default'
              run: npx prettier . --check

            - name: Build
              run: yarn expo export
              env:
                  EXPO_PUBLIC_FOSS_BUILD: ${{ matrix.variant == 'default' && 'false' || 'true' }}

            - name: Test
              if: matrix.variant == 'default'
              run: yarn test --run --coverage --reporter=junit --outputFile=test-report.junit.xml

            - name: Upload test results to Codecov
              if: ${{ !cancelled() && matrix.variant == 'default' }}
              uses: codecov/codecov-action@v5
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
                  report_type: test_results

            - name: Upload coverage reports to Codecov
              if: matrix.variant == 'default'
              uses: codecov/codecov-action@v5
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}

            - name: Expo Doctor
              if: matrix.variant == 'default'
              run: npx expo-doctor

            - name: Yarn Dedupe Check
              if: matrix.variant == 'default'
              run: yarn dedupe --check
