name: Release

on:
    push:
        tags:
            - 'v*'

jobs:
    build-and-release:
        runs-on: ubuntu-latest
        permissions:
            contents: write

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Enable Corepack
              run: corepack enable

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 24
                  cache: 'yarn'

            - name: Install dependencies
              run: yarn install --immutable

            - name: Generate License Information Check
              run: yarn generate-licenses

            - name: Setup Java
              uses: actions/setup-java@v4
              with:
                  distribution: 'zulu'
                  java-version: '17'

            - name: Set APP_VERSION
              run: echo "APP_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

            - name: Prebuild Android
              run: npx expo prebuild --platform android --clean

            - name: Build Android APK
              working-directory: android
              run: ./gradlew assembleRelease

            - name: Publish Release to GitHub
              uses: softprops/action-gh-release@v2
              with:
                  files: android/app/build/outputs/apk/release/*.apk
                  name: Release ${{ env.APP_VERSION }}
                  generate_release_notes: true
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
