name: Release

on:
    push:
        tags:
            - 'v*'

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                variant: [default, foss]
        env:
            EXPO_PUBLIC_FOSS_BUILD: ${{ matrix.variant == 'foss' && 'true' || 'false' }}
            NODE_ENV: production

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Environment and Install Dependencies
              uses: ./.github/actions/setup-environment
              with:
                  variant: ${{ matrix.variant }}

            - name: Setup Java
              uses: actions/setup-java@v4
              with:
                  distribution: 'zulu'
                  java-version: '17'

            - name: Set APP_VERSION and APP_VERSION_CODE
              run: |
                  echo "APP_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
                  echo "APP_VERSION_CODE=${{ github.run_number }}" >> $GITHUB_ENV

            - name: Prebuild Android
              run: npx expo prebuild --platform android --clean

            - name: Build Android APK
              working-directory: android
              run: ./gradlew assembleRelease

            - name: Rename APK
              run: find android/app/build/outputs/apk/release -name "*.apk" -exec mv {} android/app/build/outputs/apk/release/time-tracking-${{ matrix.variant }}.apk \;

            - name: Upload APK Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: apk-${{ matrix.variant }}
                  path: android/app/build/outputs/apk/release/time-tracking-${{ matrix.variant }}.apk
                  if-no-files-found: error

    release:
        needs: build
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Set APP_VERSION
              run: echo "APP_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

            - name: Download all APKs
              uses: actions/download-artifact@v4
              with:
                  pattern: apk-*
                  merge-multiple: true
                  path: release-apks/

            - name: Publish Release to GitHub
              uses: softprops/action-gh-release@v2
              with:
                  files: release-apks/*.apk
                  name: Release ${{ env.APP_VERSION }}
                  generate_release_notes: true
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
